# Generated by Django 3.0.7 on 2020-06-06 04:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import testapp.product


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.CategoryModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.CategoryModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_no', models.CharField(max_length=100)),
                ('variation', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(choices=[(testapp.product.Currency['USD'], 'USD'), (testapp.product.Currency['CAD'], 'CAD'), (testapp.product.Currency['EUR'], 'EUR')], max_length=8)),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.ProductModel')),
            ],
        ),
    ]
