# Generated by Django 3.0.7 on 2020-06-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200606_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productvariationmodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD'), ('EUR', 'EUR')], max_length=8),
        ),
        migrations.AlterField(
            model_name='productvariationmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='variations', to='product.ProductModel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='product.TagModel'),
        ),
    ]
